### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by aasharma90** [gruberto/PixelAccurateDepthBenchmark#1] opened 2020-05-02 12:55 UTC
Hi, 

Thanks for publishing your code and dataset. Upon registration for downloading the data however, the following error occurs -

![image](https://user-images.githubusercontent.com/27413823/80864753-338cf100-8cb7-11ea-9971-79211cc005b1.png)

Will you be able to kindly look into the matter and resolve the problem? 

Thanks again,
Aashish

**Comment by gruberto** [comment] 2020-05-11 19:05
Are you still experiencing this error? I have not heard from other people having the same issue.

**Comment by aasharma90** [comment] 2020-05-11 20:40
Hi @gruberto 

Yes, I tried just now, and it is the same error as shown in the snapshot above. Not sure what is the problem. I've also contacted my colleagues to double-check, and they have also reported the same error.

**Comment by gruberto** [comment] 2020-05-13 18:51
I cannot reproduce your bug. I can register without any problems. It might be possible that you enter some characters or a mail address that is classified as spam. Can you please try other input to the form? Without reproducing your bug I am not able to resolve this issue.

**Comment by gruberto** [comment] 2020-05-15 15:44
I could reproduce the bug now. We are working on resolving this issue. However, as a quick workaround you could use the German page version.

**Comment by aasharma90** [comment] 2020-05-17 09:15
Thanks for your feedback. I was able to register using the German page version. However, upon accessing the download URL, I get this error -
![image](https://user-images.githubusercontent.com/27413823/82140551-ff423480-9861-11ea-8b97-6cf843180962.png)

**Comment by gruberto** [comment] 2020-05-18 16:45
The registration issue is resolved. We are working on updating the invalid link.

**Comment by gruberto** [comment] 2020-05-25 14:55
The link in the mail is updated and should work now.

**Closed as completed by gruberto** 2020-05-25 14:55 UTC

**Comment by aasharma90** [comment] 2020-05-31 14:00
Thanks for resolving the problem. Both the registration and link work now.
